### ISSUE TITLE
Renaming this package

### ISSUE THREAD

**Issue by tomasvanpottelbergh** [conda-forge/darts-feedstock#1]
### Comment:

As maintainers of [Darts](https://github.com/unit8co/darts), an actively maintained Python package, we would love to have the `darts` name on conda-forge for our package, just like we have have on [PyPI](https://pypi.org/project/darts/). Currently, we are using the `u8darts` name on conda-forge, but this is confusing for our users.

Would you be open to rename this package to something like pt-darts for example? That would be very much appreciated!

**Comment by tomasvanpottelbergh** [comment]
@conda-forge/core would we able to take over this package, as it seems abandoned, and use it for our Python library `darts`? This would help our users find the right package on conda.

**Comment by beckermr** [comment]
Is this the same code base as yours? I was confused by the issue.

**Comment by tomasvanpottelbergh** [comment]
No, it isn't. [Our codebase](https://github.com/unit8co/darts) is for a popular Python timeseries library, while [the codebase behind this package](https://github.com/khanrc/pt.darts) is currently a PyTorch implementation of a research paper.

We would greatly appreciate being able to use `darts` instead of `u8darts` on conda-forge, to make the naming consistent everywhere. I don't know what's the best way forward for this, but renaming this package to pt-darts (or similar) would make sense, as its consistent with the name of the codebase behind it.

**Comment by beckermr** [comment]
Ok. We don't allow changes of this kind. Namespaces on conda-forge (and pypi) are first-come-first-serve.

**Comment by tomasvanpottelbergh** [comment]
Thanks for your quick response. I'm pretty sure we did manage to do it on PyPI, but I understand if this is the conda-forge policy.
